### ISSUE TITLE
Log entry modal dialog displays HTML encoded data for message field

### ISSUE THREAD

**Issue by jamesnetherton** [hawtio/hawtio-log#2]
![logs-modal](https://user-images.githubusercontent.com/4721408/42033759-d7102b30-7ad5-11e8-92f5-ab18a8e67fca.png)

**Comment by abkieling** [comment]
I'll fix it. Note that hawtio-log has been moved to hawtio-jmx.

**Comment by abkieling** [comment]
Recreated the issue in hawtio-jmx
